version: "3"

services:
  backend:
      build: ./backend/Django/.devcontainer
      ports:
        - 8000:8000
      command: >
        sh -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./backend/Django/Project:/app
      depends_on:
        - db
  db:
      image: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres